name = input("enter your name = ")
collage =input ("enter your collage =")
age = input ('enter your age = ')
city = input ('enter your city = ')
print(name, type(name))
print(collage, type(collage))
print(age, type(age))
print(city, type(city))